input {
    tcp {
        port => 5044
        codec => json_lines
    }
}

output {
    elasticsearch {
        hosts => ["http://${ELASTIC_HOST}:${ELASTIC_PORT}"]
        index => "application-logs-%{+YYYY.MM.dd}"
    }
}