# 유레카를 통해 동적으로 서비스 가져오기
scrape_configs:
  - job_name: 'eureka'
    metrics_path: '/actuator/prometheus'
    eureka_sd_configs:
      # 여기로 들어가서 유레카에서 관리하는 서비스를 찾음
      - server: 'http://service-registry:8761/eureka'
        refresh_interval: 30s
    relabel_configs:
      # ex)AUTH-SERVICE
      - source_labels: [ __meta_eureka_app_name ]
        target_label: job
      # ex)localhost:8080
      - source_labels: [ __meta_eureka_app_instance_id ]
        target_label: instance
      - source_labels: [ __meta_eureka_app_instance_id ]
        target_label: __address__