server:
  port: 8080

spring:
  application:
    name: order-service
  profiles:
    active: prod

  config:
    import: optional:configserver:http://${CONFIG_HOST}:${CONFIG_PORT}
  cloud:
    config:
      profile: prod
    # label: main